### ISSUE TITLE
the board constructorh

### ISSUE THREAD

**Issue by hanaBainbridge** [ConnorADunedin63/Cluedo-Project#7]
hey connor i was wondering if you could add a check in the board constructor checking to see if the paremter i think it called numPlayers or something? is zero because i need to make a board object in one of my classes so that i can  acess the getter methods. 
thanks

**Comment by ConnorADunedin63** [comment]
Hey Hana,
I know what you want to do but that will not work because all the fields are unique to that instance of the board class.
So if you create a new instance yes it will have the same fields but the values will not be the same.

A possible solution is to transfer the makeSuggestion and makeAccusation methods to the Board class itself so we have access to the data.

Or another way is to pass the ArrayLists as a parameter of the methods. So for example we could pass the character, weapon and room cards that are remaining to the method and let the method handle asking the player what character weapon and room they want to select and the choices are returned to the Board class where the other players refute the suggestion or the accusation is checked.

Is any of this making sense?
What do you think?

Thanks
Connor

**Comment by ConnorADunedin63** [comment]
I prefer the second way because I feel that the Player class should handle it.

**Comment by ConnorADunedin63** [comment]
Another option is to pass the Board in as a parameter in the Player constructor, eg new Player(this)
